### ISSUE TITLE
New modella recursive toJSON() messes up dates

### ISSUE THREAD

**Issue by paulbdavis** [modella/mongo#16]
Dates are not having `toJSON()` called on them as part of the new modella recursive `toJSON()` method. This is causing `Date` objects to be stored in mongo as strings, rather than `ISODate` objects.

Perhaps modella-mongo should check for the options `{type: 'date'}` and `{type: Date}` to see if they should be turned _back_ into date objects before inserting/updating

**Comment by rschmukler** [comment]
Thanks @paulbdavis
