### ISSUE TITLE
use mquery

### ISSUE THREAD

**Issue by yields** [modella/mongo#4]
something like

``` js
User
  .query()
  .where('foo', 'baz')
  .find(fn);
```

?

**Comment by rschmukler** [comment]
@yields can you elaborate a bit on this? I haven't seen this syntax for mongo, do you have a lib that implements something similar to what you like?

**Comment by yields** [comment]
i guess we can use https://github.com/aheckmann/mquery, i didn't investigate, but i think it just needs a "native" mongo collection as an argument.

**Comment by rschmukler** [comment]
Interesting. One of the things I was considering was removing the abstraction all-together and going to just `mongoskin` -- you think the mquery abstraction is worth it?

**Comment by yields** [comment]
yeah, mquery makes large queries elegant, i think mquery will work with monk https://github.com/LearnBoost/monk/blob/master/lib/collection.js#L27 and https://github.com/kissjs/node-mongoskin/blob/master/lib/mongoskin/collection.js#L124.

so it doesn't matter which abstraction we use :)

**Comment by rschmukler** [comment]
@yields Actually, after reading through the docs, mquery looks bomb...

I am thinking of dropping monk for just plain mongoskin though.

**Comment by rschmukler** [comment]
One issue I am thinking of though, is how do we ensure that we get back modella instances... We can monkey patch `.exec` but what about the other ones like `.find` etc?

**Comment by rschmukler** [comment]
Actually, I have an idea...

**Comment by yields** [comment]
i think once a user uses `.query()` it's obvious he isn't going to get modella instance, but we can always look at what mongoose does, since it uses mquery too.

looking at mongoskin, it doesn't seem to buffer callbacks until a connection to the database is established,
but i guess we can implement our own callback "buffering"

**Comment by rschmukler** [comment]
@yields We could actually probably get instances, if we wanted to out of `.query()`. Would that be valuable do you think?

**Comment by yields** [comment]
can you elaborate more, why would we need modella instance out of query methods.

**Comment by rschmukler** [comment]
For example: `User.query().where('age').gte(20).exec(fn)` returning modella instances would be useful, since otherwise the first line is likely to be `var users = new User(records);` anyway...

**Comment by yields** [comment]
oh yeah, i think all records should be modella instances by default.
i think we might need to wrap `mquery` to implement stuff like `.stream()` and `.lean()` (like mongoose).

**Comment by rschmukler** [comment]
Yeah, that's what I am thinking...

**Comment by rschmukler** [comment]
@yields I implemented mquery, let me know what you think. Good call man, this looks awesome.

**Comment by yields** [comment]
@rschmukler that's awesome!
